version: '3.8'
services:
  runmatch-db:
    image: mysql:8.0
    container_name: runmatch-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: runmatch
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - runmatch-net

  runmatch-redis:
    image: redis:7-alpine
    container_name: runmatch-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - runmatch-net

networks:
  runmatch-net:
    driver: bridge
