spring:
  application:
    name: runner-api

  # --- MySQL 데이터베이스 설정 ---
  datasource:
    url: jdbc:mysql://localhost:3306/runmatch?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  # --- JPA (Hibernate) 설정 ---
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # --- Redis 설정 ---
  data:
    redis:
      host: localhost
      port: 6379

  # --- GMAIL 설정 (spring: 바로 아래에 위치해야 함) ---
  mail:
    host: smtp.gmail.com
    port: 587
    username: dbsgusrl09@gmail.com
    password: "fqlf udbx uayf gdns"
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

# --- 로그 설정 ---
logging:
  level:
    org.hibernate.SQL: debug